#!/bin/bash
# Author: M. EL Aabaribaoune (@um6p)
#
# migrate.sh — Reorganize NoahMP_Morocco directory structure
#
# This script migrates from the flat directory layout to the
# organized structure with: src/, arch/, configs/, scripts/,
# data/, experiments/, postproc/, logs/, docs/
#
# IMPORTANT: Run from the NoahMP_Morocco root directory.
# The script creates the new structure and moves files,
# then updates all paths in config files.

set -e

BASEDIR="$(pwd)"

echo "============================================="
echo " NoahMP_Morocco Directory Migration"
echo "============================================="
echo " Base directory: $BASEDIR"
echo ""

# Safety check
if [ ! -f "lis.config.opl" ] || [ ! -d "lisf" ]; then
    echo "ERROR: Must run from the NoahMP_Morocco root directory."
    echo "Expected to find: lis.config.opl, lisf/"
    exit 1
fi

# ============================================================
# STEP 1: Create directory structure
# ============================================================
echo "[1/7] Creating directory structure..."

mkdir -p src
mkdir -p configs
mkdir -p scripts/jobs
mkdir -p scripts/download
mkdir -p scripts/fix
mkdir -p data/met_forcing
mkdir -p data/land_params
mkdir -p data/observations
mkdir -p data/pert_package
mkdir -p experiments/OPL
mkdir -p experiments/DA
mkdir -p experiments/scalability
mkdir -p postproc/scripts
mkdir -p postproc/figures
mkdir -p logs/slurm
mkdir -p docs

echo "   Done."

# ============================================================
# STEP 2: Move source code
# ============================================================
echo "[2/7] Moving source code..."

mv lisf src/lisf
echo "   lisf/ → src/lisf/"

# ============================================================
# STEP 3: Move configs
# ============================================================
echo "[3/7] Moving configuration files..."

mv lis.config.opl configs/
mv lis.config.da configs/
mv ldt.config configs/
mv MODEL_OUTPUT_LIST.TBL configs/
# forcing_variables.txt stays in data/ since it's input data
echo "   Configs → configs/"

# ============================================================
# STEP 4: Move scripts
# ============================================================
echo "[4/7] Moving scripts..."

# Job scripts
mv job_1_ldt.sh scripts/jobs/
mv job_2_lis_opl.sh scripts/jobs/
mv job_3_lis_da.sh scripts/jobs/

# Download scripts
mv download_smap.py scripts/download/
mv download_merra2.py scripts/download/
mv download_parameters.py scripts/download/
mv reorganize_merra2.sh scripts/download/

# Fix scripts
mv fix_gtopo.py scripts/fix/
mv fix_mptable.py scripts/fix/

# Scalability scripts
if [ -d "scalability_test" ]; then
    mv scalability_test/job_scalability.sh scripts/jobs/
    mv scalability_test/submit_all.sh scripts/
    mv scalability_test/generate_configs.sh scripts/
    # Move scalability configs
    if [ -d "scalability_test/configs" ]; then
        mv scalability_test/configs configs/scalability/
    fi
    # Move scalability output
    if [ -d "scalability_test/output" ]; then
        mv scalability_test/output/* experiments/scalability/ 2>/dev/null || true
    fi
    if [ -d "scalability_test/logs" ]; then
        mv scalability_test/logs/* logs/slurm/ 2>/dev/null || true
    fi
    rm -rf scalability_test
fi

# Remove RegCM job (reference only, not part of project)
if [ -f "job_regcm.sh" ]; then
    mv job_regcm.sh docs/job_regcm_reference.sh
fi

echo "   Scripts → scripts/"

# ============================================================
# STEP 5: Move data
# ============================================================
echo "[5/7] Moving data..."

# Met forcing (keep MET_FORCING which has 89G, remove empty met_forcing)
if [ -d "input/MET_FORCING" ]; then
    mv input/MET_FORCING/MERRA2 data/met_forcing/MERRA2
fi
# Remove empty duplicate
rm -rf input/met_forcing 2>/dev/null || true
rm -rf input/MET_FORCING 2>/dev/null || true

# Observations (keep RS_DATA which has 2.9G, remove empty rs_data)
if [ -d "input/RS_DATA" ]; then
    mv input/RS_DATA/SMAP data/observations/SMAP
fi
rm -rf input/rs_data 2>/dev/null || true
rm -rf input/RS_DATA 2>/dev/null || true

# Land parameters
if [ -d "input/noah_2dparms" ]; then
    mv input/noah_2dparms data/land_params/noah_2dparms
fi
if [ -d "input/topo_parms" ]; then
    mv input/topo_parms data/land_params/topo_parms
fi

# Perturbation package (DA)
if [ -d "input/pert_package" ]; then
    mv input/pert_package/* data/pert_package/ 2>/dev/null || true
    rm -rf input/pert_package
fi

# Forcing variables list
if [ -f "input/forcing_variables.txt" ]; then
    mv input/forcing_variables.txt configs/
fi

# LIS input file (generated by LDT)
if [ -f "lis_input.d01.nc" ]; then
    mv lis_input.d01.nc data/
fi

# SMAP filelist
if [ -f "SMAP_filelist.dat" ]; then
    mv SMAP_filelist.dat data/observations/
fi

# Clean up empty input dir
rm -rf input 2>/dev/null || true

echo "   Data → data/"

# ============================================================
# STEP 6: Move outputs, logs, docs
# ============================================================
echo "[6/7] Moving outputs, logs, docs..."

# Experiment outputs
if [ -d "OUTPUT_OPL" ]; then
    mv OUTPUT_OPL/* experiments/OPL/ 2>/dev/null || true
    rm -rf OUTPUT_OPL
fi
if [ -d "OUTPUT_DA" ]; then
    mv OUTPUT_DA/* experiments/DA/ 2>/dev/null || true
    rm -rf OUTPUT_DA
fi

# SLURM logs
if [ -d "slurm_logs" ]; then
    mv slurm_logs/* logs/slurm/ 2>/dev/null || true
    rm -rf slurm_logs
fi

# Download logs
for logfile in download_smap.log download_merra2.log download_params.log ldt_run.log lis_opl_run.log lis_da_run.log MaskParamFill.log; do
    if [ -f "$logfile" ]; then
        mv "$logfile" logs/
    fi
done

# Post-processing
if [ -d "postproc" ]; then
    mv postproc/plot_all.py postproc/scripts/ 2>/dev/null || true
    mv postproc/*.png postproc/figures/ 2>/dev/null || true
fi

# Documentation
mv TROUBLESHOOTING_LOG.md docs/ 2>/dev/null || true
mv COMPILATION_AND_STATUS_SUMMARY.txt docs/ 2>/dev/null || true

echo "   Done."

# ============================================================
# STEP 7: Update paths in config files
# ============================================================
echo "[7/7] Updating paths in config files..."

# --- lis.config.opl ---
sed -i \
    -e 's|./input/forcing_variables.txt|./configs/forcing_variables.txt|' \
    -e 's|"OUTPUT_OPL"|"experiments/OPL"|' \
    -e 's|"OUTPUT_OPL/lislog"|"experiments/OPL/lislog"|' \
    -e 's|./input/noah_2dparms/|./data/land_params/noah_2dparms/|g' \
    -e 's|./lis_input.d01.nc|./data/lis_input.d01.nc|g' \
    -e 's|./input/MET_FORCING/MERRA2/|./data/met_forcing/MERRA2/|' \
    -e "s|'./MODEL_OUTPUT_LIST.TBL'|'./configs/MODEL_OUTPUT_LIST.TBL'|" \
    -e 's|./input/LS_PARAMETERS/noahmp_parms/|./data/land_params/noah_2dparms/|g' \
    configs/lis.config.opl

echo "   Updated configs/lis.config.opl"

# --- lis.config.da ---
sed -i \
    -e 's|./input/forcing_variables.txt|./configs/forcing_variables.txt|' \
    -e 's|"OUTPUT_DA"|"experiments/DA"|' \
    -e 's|"OUTPUT_DA/lislog"|"experiments/DA/lislog"|' \
    -e 's|./input/noah_2dparms/|./data/land_params/noah_2dparms/|g' \
    -e 's|./lis_input.d01.nc|./data/lis_input.d01.nc|g' \
    -e 's|./input/MET_FORCING/MERRA2/|./data/met_forcing/MERRA2/|' \
    -e 's|./input/pert_package/|./data/pert_package/|g' \
    -e 's|./input/RS_DATA/SMAP/SPL3SMP.009|./data/observations/SMAP/SPL3SMP.009|' \
    -e "s|'./MODEL_OUTPUT_LIST.TBL'|'./configs/MODEL_OUTPUT_LIST.TBL'|" \
    -e 's|./input/LS_PARAMETERS/noahmp_parms/|./data/land_params/noah_2dparms/|g' \
    configs/lis.config.da

echo "   Updated configs/lis.config.da"

# --- ldt.config ---
sed -i \
    -e 's|./lis_input.d01.nc|./data/lis_input.d01.nc|' \
    -e 's|./input/noah_2dparms/|./data/land_params/noah_2dparms/|g' \
    -e 's|./input/topo_parms/|./data/land_params/topo_parms/|g' \
    configs/ldt.config

echo "   Updated configs/ldt.config"

# --- Job scripts (update binary paths and config paths) ---
# job_1_ldt.sh
sed -i \
    -e 's|./lisf/ldt/make/LDT ldt.config|./src/lisf/ldt/make/LDT configs/ldt.config|' \
    -e 's|module purge|source arch/arch_toubkal.env|' \
    -e '/module load/d' \
    scripts/jobs/job_1_ldt.sh

echo "   Updated scripts/jobs/job_1_ldt.sh"

# job_2_lis_opl.sh
sed -i \
    -e 's|./lisf/lis/LIS -f lis.config.opl|mpirun -n $SLURM_NTASKS ./src/lisf/lis/LIS -f configs/lis.config.opl|' \
    -e 's|module purge|source arch/arch_toubkal.env|' \
    -e '/module load/d' \
    scripts/jobs/job_2_lis_opl.sh

echo "   Updated scripts/jobs/job_2_lis_opl.sh"

# job_3_lis_da.sh
sed -i \
    -e 's|./lisf/lis/LIS -f lis.config.da|mpirun -n $SLURM_NTASKS ./src/lisf/lis/LIS -f configs/lis.config.da|' \
    -e 's|module purge|source arch/arch_toubkal.env|' \
    -e '/module load/d' \
    scripts/jobs/job_3_lis_da.sh

echo "   Updated scripts/jobs/job_3_lis_da.sh"

echo ""
echo "============================================="
echo " Migration completed successfully!"
echo "============================================="
echo ""
echo " New structure:"
echo "   arch/          — Environment (arch_toubkal.env)"
echo "   src/           — Source code (lisf/)"
echo "   configs/       — LIS/LDT configs"
echo "   scripts/       — Job scripts & utilities"
echo "   data/          — Input data"
echo "   experiments/   — Output by experiment"
echo "   postproc/      — Post-processing & figures"
echo "   logs/          — All logs"
echo "   docs/          — Documentation"
echo ""
echo " Next steps:"
echo "   1. Verify configs:  grep -r './input/' configs/"
echo "   2. Run LDT:         sbatch scripts/jobs/job_1_ldt.sh"
echo "   3. Run OPL:         sbatch --nodes=1 scripts/jobs/job_2_lis_opl.sh"
echo "   4. Run DA:          sbatch --nodes=1 scripts/jobs/job_3_lis_da.sh"
echo "============================================="
