import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import os
import argparse

def main():
    parser = argparse.ArgumentParser(description="Hydrological response diagnostics")
    parser.add_argument('--input-parquet', type=str, 
                        default='/home/mohammad.elaabaribao/lustre/empowermed-ahl6xm8o7mg/users/mohammad.elaabaribao/IA_SM_assim/data/processed/monthly_pixel_dataset_2016_2020_static.parquet',
                        help='Input dataset (generated by IA_SM_assim and consumed by hydrological postproc)')
    parser.add_argument('--output-root', type=str, default='matrix_2016_2020/outputs',
                        help='Root output directory')
    parser.add_argument('--overwrite', action='store_true', help='Overwrite existing files')
    parser.add_argument('--dry-run', action='store_true', help='Print what would be done without writing')
    args = parser.parse_args()

    print(f"Reading data from: {args.input_parquet}")
    if not args.dry_run:
        df = pd.read_parquet(args.input_parquet)
    else:
        # Mock dataframe for dry-run
        df = pd.DataFrame({'time': ['2016-01-01'], 'lat': [0], 'lon': [0], 'days': [31], 'month': [1]})
        for exp in ['OPL', 'DA_NoCDF', 'DA_CDF']:
            for base in ['SSM', 'RZSM', 'Evap_tavg', 'Qs_tavg', 'Qsb_tavg', 'Rainf_tavg']:
                df[f'{base}_{exp}'] = 0.0

    # Variables mapping
    var_map = {
        'SSM': ('SSM_OPL', 'SSM_DA_NoCDF', 'SSM_DA_CDF'),
        'RZSM': ('RZSM_OPL', 'RZSM_DA_NoCDF', 'RZSM_DA_CDF'),
        'ET': ('Evap_tavg_OPL', 'Evap_tavg_DA_NoCDF', 'Evap_tavg_DA_CDF'),
        'Qs': ('Qs_tavg_OPL', 'Qs_tavg_DA_NoCDF', 'Qs_tavg_DA_CDF'),
        'Qsb': ('Qsb_tavg_OPL', 'Qsb_tavg_DA_NoCDF', 'Qsb_tavg_DA_CDF'),
        'P': ('Rainf_tavg_OPL', 'Rainf_tavg_DA_NoCDF', 'Rainf_tavg_DA_CDF')
    }

    # 2. Conversion mm/month -> mm/day
    days_in_month = {1:31, 2:28.25, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9:30, 10:31, 11:30, 12:31}
    if 'month' not in df.columns:
        df['month'] = pd.to_datetime(df['time']).dt.month
    df['days'] = df['month'].map(days_in_month)

    for v in ['ET', 'Qs', 'Qsb', 'P']:
        for c in var_map[v]:
            if c in df.columns:
                df[c + '_mm_day'] = df[c] / df['days']

    # Compute total runoff
    for exp in ['OPL', 'DA_NoCDF', 'DA_CDF']:
        if f'Qs_tavg_{exp}_mm_day' in df.columns:
            df[f'Qtotal_{exp}_mm_day'] = df[f'Qs_tavg_{exp}_mm_day'] + df[f'Qsb_tavg_{exp}_mm_day']

    df_djf = df[df['month'].isin([12, 1, 2])]
    df_jja = df[df['month'].isin([6, 7, 8])]
    df_ann = df

    # Directories
    fig_hydro_dir = os.path.join(args.output_root, 'figures/hydrological_response')
    fig_runoff_dir = os.path.join(args.output_root, 'figures/runoff_partitioning')
    fig_wb_dir = os.path.join(args.output_root, 'figures/water_balance')
    tables_dir = os.path.join(args.output_root, 'tables')
    
    for d in [fig_hydro_dir, fig_runoff_dir, fig_wb_dir, tables_dir]:
        if not args.dry_run:
            os.makedirs(d, exist_ok=True)
        else:
            print(f"[DRY RUN] Would create directory: {d}")

    def save_fig(fig, filepath):
        if args.dry_run:
            print(f"[DRY RUN] Would save figure: {filepath}")
            plt.close()
        elif os.path.exists(filepath) and not args.overwrite:
            print(f"Skipping {filepath} (exists, use --overwrite to replace)")
            plt.close()
        else:
            plt.savefig(filepath, dpi=150, bbox_inches='tight', facecolor='white')
            plt.close()
            print(f"Saved {filepath}")

    def plot_hydrological_response(subset_df, period_name, filepath):
        if args.dry_run:
            print(f"[DRY RUN] Plotting {period_name} into {filepath}")
            return

        if os.path.exists(filepath) and not args.overwrite:
            print(f"Skipping {filepath}")
            return
            
        fig, axes = plt.subplots(3, 6, figsize=(24, 12))
        mean_df = subset_df.groupby(['lat', 'lon']).mean().reset_index()
        
        variables = [
            ('SSM', 'SSM', 'SSM', 'm3/m3', 0.05),
            ('RZSM', 'RZSM', 'RZSM', 'm3/m3', 0.05),
            ('ET', 'Evap_tavg', '_mm_day', 'mm/day', 0.5),
            ('Qtotal', 'Qtotal', '_mm_day', 'mm/day', 0.2),
            ('Qs', 'Qs_tavg', '_mm_day', 'mm/day', 0.1),
            ('Qsb', 'Qsb_tavg', '_mm_day', 'mm/day', 0.2)
        ]
        experiments = [
            ('DA_NoCDF - OPL', 'DA_NoCDF', 'OPL'),
            ('DA_CDF - OPL', 'DA_CDF', 'OPL'),
            ('DA_NoCDF - DA_CDF', 'DA_NoCDF', 'DA_CDF')
        ]
        
        for c, (title, base_var, suffix, unit, vmax) in enumerate(variables):
            for r, (row_title, exp1, exp2) in enumerate(experiments):
                ax = axes[r, c]
                ax.set_aspect('equal')
                ax.set_facecolor('white')
                
                if base_var == 'Qtotal':
                    col1 = f'Qtotal_{exp1}{suffix}'
                    col2 = f'Qtotal_{exp2}{suffix}'
                else:
                    col1 = f'{base_var}_{exp1}'
                    if suffix == '_mm_day': col1 += suffix
                    col2 = f'{base_var}_{exp2}'
                    if suffix == '_mm_day': col2 += suffix
                
                if col1 in mean_df.columns and col2 in mean_df.columns:
                    diff = mean_df[col1] - mean_df[col2]
                    sc = ax.scatter(mean_df['lon'], mean_df['lat'], c=diff, cmap='RdBu', 
                                    vmin=-vmax, vmax=vmax, s=15, marker='s', edgecolors='none')
                    d_min, d_mean, d_max = diff.min(), diff.mean(), diff.max()
                    ax.text(0.05, 0.05, f"Min: {d_min:.3f}\\nMean: {d_mean:.3f}\\nMax: {d_max:.3f}", 
                            transform=ax.transAxes, fontsize=9, bbox=dict(facecolor='white', alpha=0.7))
                ax.set_title(f"{row_title}\\nΔ{title}")
                ax.axis('off')
                
                if r == 2 and 'sc' in locals():
                    cbar = plt.colorbar(sc, ax=axes[:, c], orientation='horizontal', fraction=0.05, pad=0.1)
                    cbar.set_label(f"Δ{title} ({unit})")

        plt.tight_layout()
        save_fig(fig, filepath)

    # Output figures for response
    plot_hydrological_response(df_ann, "Annual", os.path.join(fig_hydro_dir, "manuscript_hydro_response_states_ET_annual_2016_2020.png"))
    plot_hydrological_response(df_djf, "DJF", os.path.join(fig_hydro_dir, "manuscript_hydro_response_states_ET_DJF_2016_2020.png"))
    plot_hydrological_response(df_jja, "JJA", os.path.join(fig_hydro_dir, "manuscript_hydro_response_states_ET_JJA_2016_2020.png"))
    
    # 4. Summary Table
    tables_path = os.path.join(tables_dir, 'hydrological_response_summary_2016_2020.csv')
    if args.dry_run:
        print(f"[DRY RUN] Would save table: {tables_path}")
    elif not os.path.exists(tables_path) or args.overwrite:
        print("Generating summary table...")
        summary_data = []
        periods = [('annual', df_ann), ('DJF', df_djf), ('JJA', df_jja)]
        variables = [
            ('SSM', 'SSM', 'SSM', 'm3/m3'), ('RZSM', 'RZSM', 'RZSM', 'm3/m3'),
            ('ET', 'Evap_tavg', '_mm_day', 'mm/day'), ('total_runoff', 'Qtotal', '_mm_day', 'mm/day'),
            ('surface_runoff', 'Qs_tavg', '_mm_day', 'mm/day'), ('baseflow', 'Qsb_tavg', '_mm_day', 'mm/day')
        ]
        experiments = [
            ('DA-NoCDF_minus_OPL', 'DA_NoCDF', 'OPL'),
            ('DA-CDF_minus_OPL', 'DA_CDF', 'OPL'),
            ('DA-NoCDF_minus_DA-CDF', 'DA_NoCDF', 'DA_CDF')
        ]
        for p_name, p_df in periods:
            mean_df = p_df.groupby(['lat', 'lon']).mean().reset_index()
            for exp_name, exp1, exp2 in experiments:
                for v_name, base_var, suffix, unit in variables:
                    if base_var == 'Qtotal':
                        col1 = f'Qtotal_{exp1}{suffix}'
                        col2 = f'Qtotal_{exp2}{suffix}'
                    else:
                        col1 = f'{base_var}_{exp1}'
                        if suffix == '_mm_day': col1 += suffix
                        col2 = f'{base_var}_{exp2}'
                        if suffix == '_mm_day': col2 += suffix
                    if col1 in mean_df.columns and col2 in mean_df.columns:
                        diff = mean_df[col1] - mean_df[col2]
                        summary_data.append({
                            'experiment_difference': exp_name, 'period': p_name, 'variable': v_name,
                            'unit': unit, 'min': diff.min(), 'mean': diff.mean(), 'median': diff.median(),
                            'max': diff.max(), 'std': diff.std(),
                            'percent_positive': (diff > 0).mean() * 100, 'percent_negative': (diff < 0).mean() * 100,
                            'n_pixels': len(diff)
                        })
        sum_df = pd.DataFrame(summary_data)
        sum_df.to_csv(tables_path, index=False)
        print(f"Saved {tables_path}")
    else:
        print(f"Skipping {tables_path}")

    # 5. Water Balance
    wb_table_path = os.path.join(tables_dir, 'flux_only_water_balance_annual_seasonal_2016_2020.csv')
    if args.dry_run:
        print(f"[DRY RUN] Would save table: {wb_table_path}")
    elif not os.path.exists(wb_table_path) or args.overwrite:
        print("Generating water balance...")
        wb_data = []
        for p_name, p_df in periods:
            mean_df = p_df.groupby(['lat', 'lon']).mean().reset_index()
            for exp in ['OPL', 'DA_NoCDF', 'DA_CDF']:
                if f'Rainf_tavg_{exp}_mm_day' in mean_df.columns:
                    p = mean_df[f'Rainf_tavg_{exp}_mm_day'].mean()
                    et = mean_df[f'Evap_tavg_{exp}_mm_day'].mean()
                    qs = mean_df[f'Qs_tavg_{exp}_mm_day'].mean()
                    qsb = mean_df[f'Qsb_tavg_{exp}_mm_day'].mean()
                    qtot = qs + qsb
                    residual = p - et - qtot
                    wb_data.append({
                        'period': p_name, 'experiment': exp, 'P': p, 'ET': et,
                        'Qs': qs, 'Qsb': qsb, 'Qtotal': qtot, 'flux_only_residual': residual
                    })
        wb_df = pd.DataFrame(wb_data)
        wb_df.to_csv(wb_table_path, index=False)
        print(f"Saved {wb_table_path}")

    wb_fig_path = os.path.join(fig_wb_dir, 'manuscript_flux_only_water_balance_2016_2020.png')
    if args.dry_run:
        print(f"[DRY RUN] Would plot to {wb_fig_path}")
    elif not os.path.exists(wb_fig_path) or args.overwrite:
        if 'wb_df' in locals():
            fig, axes = plt.subplots(1, 3, figsize=(18, 5))
            for i, p_name in enumerate(['annual', 'DJF', 'JJA']):
                ax = axes[i]
                sub = wb_df[wb_df['period'] == p_name]
                x = np.arange(3)
                width = 0.2
                ax.bar(x - width*1.5, sub['P'], width, label='P')
                ax.bar(x - width*0.5, sub['ET'], width, label='ET')
                ax.bar(x + width*0.5, sub['Qtotal'], width, label='Qtotal')
                ax.bar(x + width*1.5, sub['flux_only_residual'], width, label='Residual')
                ax.set_xticks(x)
                ax.set_xticklabels(sub['experiment'])
                ax.set_title(f"Water Balance ({p_name})")
                ax.set_ylabel("mm/day")
                if i == 0: ax.legend()
            plt.tight_layout()
            save_fig(fig, wb_fig_path)

    # 6. Precip/Runoff components
    def plot_precip_runoff(exp, filename):
        filepath = os.path.join(fig_runoff_dir, filename)
        if args.dry_run:
            print(f"[DRY RUN] Would plot to {filepath}")
            return
        if os.path.exists(filepath) and not args.overwrite:
            print(f"Skipping {filepath}")
            return
            
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))
        mean_df = df_ann.groupby(['lat', 'lon']).mean().reset_index()
        vars_to_plot = [
            (f'Rainf_tavg_{exp}_mm_day', 'Precipitation (IMERG)', 0, 5),
            (f'Qtotal_{exp}_mm_day', 'Total Runoff', 0, 1),
            (f'Qsb_tavg_{exp}_mm_day', 'Baseflow', 0, 1)
        ]
        for ax, (var, title, vmin, vmax) in zip(axes, vars_to_plot):
            ax.set_aspect('equal')
            ax.set_facecolor('white')
            if var in mean_df.columns:
                sc = ax.scatter(mean_df['lon'], mean_df['lat'], c=mean_df[var], cmap='viridis', 
                                vmin=vmin, vmax=vmax, s=15, marker='s', edgecolors='none')
                ax.set_title(title)
                plt.colorbar(sc, ax=ax, orientation='horizontal', fraction=0.05, pad=0.1, label='mm/day')
            ax.axis('off')
        plt.suptitle(f"{exp} Components")
        plt.tight_layout()
        save_fig(fig, filepath)

    plot_precip_runoff('DA_NoCDF', 'manuscript_assim_diagnostics_precip_runoff_components_DA_NoCDF_IMERG_2016_2020.png')
    plot_precip_runoff('DA_CDF', 'manuscript_assim_diagnostics_precip_runoff_components_DA_CDF_IMERG_2016_2020.png')

    print("All tasks completed.")

if __name__ == '__main__':
    main()
