#define USE_NETCDF4 
#define USE_GRIBAPI 
#define USE_ECCODES 
#undef USE_HDF4 
#undef USE_HDFEOS2 
#define USE_HDF5 
#undef AFWA_GRIB_CONFIGS 
#undef USE_MATLAB_SUPPORT 
#undef USE_GDAL 
#undef INC_WATER_PTS
#undef USE_GRIB2
#undef SPMD
