"""
suggested_water_budget_analysis.py

Objective: Provide preliminary post-processing routines comparing Open Loop (OPL) 
and Data Assimilation (DA) experiments. Inspired by the methodology in 
Ahmad et al. (2024), this script focuses on:
1. Soil Moisture Increments & Time Series 
2. Total Runoff Decomposition (Surface vs. Baseflow)
3. Approximating Terrestrial Water Storage Anomalies (TWSA)
4. Evapotranspiration (ET) differences.

Note: This is an analytical template for evaluating the 3-day test and 
can be scaled for the full multi-year 2015-2020 runs.
"""

import os
import glob
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# --- 1. CONFIGURATION ---
# Replace with actual paths generated by the LIS run
DIR_OPL = "/path/to/LIS/OUTPUT/OPL"
DIR_DA = "/path/to/LIS/OUTPUT/DA"
OUT_DIR = "./preliminary_figs"

os.makedirs(OUT_DIR, exist_ok=True)

def load_lis_outputs(dir_path):
    """
    Loads daily LIS outputs into an xarray dataset.
    Assumes standard LIS netCDF format (e.g., LIS_HIST_*.nc).
    """
    files = sorted(glob.glob(os.path.join(dir_path, "LIS_HIST_*.nc")))
    if not files:
        print(f"Warning: No netCDF files found in {dir_path}")
        return None
    ds = xr.open_mfdataset(files, combine='by_coords')
    return ds

def compute_budget_and_differences(ds_opl, ds_da):
    """
    Computes diagnostic variables and differences (DA - OPL).
    """
    results = {}
    
    # 1. Total Soil Moisture (Sum over layers)
    # LIS usually has SoilMoist_tavg with dimensions (time, SoilMoist_profiles, lat, lon)
    if 'SoilMoist_tavg' in ds_opl:
        sm_opl = ds_opl['SoilMoist_tavg'].sum(dim='SoilMoist_profiles')
        sm_da = ds_da['SoilMoist_tavg'].sum(dim='SoilMoist_profiles')
        results['SM_Diff'] = sm_da - sm_opl
        results['SM_OPL'] = sm_opl
        results['SM_DA'] = sm_da

    # 2. Runoff Decomposition (Qs = Surface, Qsb = Subsurface/Baseflow)
    if 'Qs_tavg' in ds_opl and 'Qsb_tavg' in ds_opl:
        results['Qs_Diff'] = ds_da['Qs_tavg'] - ds_opl['Qs_tavg']
        results['Qsb_Diff'] = ds_da['Qsb_tavg'] - ds_opl['Qsb_tavg']
        
        # Total Runoff Ratio = Qs / (Qs + Qsb) -> How DA shifts the partitioning
        tot_ro_opl = ds_opl['Qs_tavg'] + ds_opl['Qsb_tavg']
        tot_ro_da = ds_da['Qs_tavg'] + ds_da['Qsb_tavg']
        
        # Avoid division by zero
        results['Runoff_Fraction_OPL'] = ds_opl['Qs_tavg'] / tot_ro_opl.where(tot_ro_opl > 0)
        results['Runoff_Fraction_DA'] = ds_da['Qs_tavg'] / tot_ro_da.where(tot_ro_da > 0)
        results['Runoff_Fraction_Diff'] = results['Runoff_Fraction_DA'] - results['Runoff_Fraction_OPL']

    # 3. Terrestrial Water Storage Anomaly (TWSA Proxy)
    # TWSA ≈ Δ(Soil Moisture) + Δ(Canopy Water) + Δ(Groundwater)
    # If SIMGM is used, WaterTableD_tavg or TWS_tavg might be available.
    if 'CanopInt_tavg' in ds_opl and 'SoilMoist_tavg' in ds_opl:
        twsa_opl = sm_opl + ds_opl['CanopInt_tavg']
        twsa_da = sm_da + ds_da['CanopInt_tavg']
        
        # Add Groundwater if available
        if 'TWS_tavg' in ds_opl:
             twsa_opl = ds_opl['TWS_tavg']
             twsa_da = ds_da['TWS_tavg']
        
        results['TWSA_Diff'] = twsa_da - twsa_opl
        
    # 4. Evapotranspiration
    if 'Evap_tavg' in ds_opl:
        results['ET_Diff'] = ds_da['Evap_tavg'] - ds_opl['Evap_tavg']

    return results

def plot_spatial_differences(results):
    """
    Generates a multipanel spatial map of the mean differences (DA - OPL)
    over the analysis period.
    """
    variables_to_plot = {
        'SM_Diff': 'Mean Total Soil Moisture Diff (DA-OPL)',
        'Qs_Diff': 'Mean Surface Runoff Diff (DA-OPL)',
        'Qsb_Diff': 'Mean Baseflow Diff (DA-OPL)',
        'ET_Diff': 'Mean ET Diff (DA-OPL)',
        'TWSA_Diff': 'Mean TWSA Proxy Diff (DA-OPL)'
    }

    fig, axes = plt.subplots(3, 2, figsize=(15, 12), subplot_kw={'projection': ccrs.PlateCarree()})
    axes = axes.flatten()

    idx = 0
    for var, title in variables_to_plot.items():
        if var in results:
            ax = axes[idx]
            # Calculate time mean
            data_mean = results[var].mean(dim='time')
            
            # Plot
            im = data_mean.plot(ax=ax, transform=ccrs.PlateCarree(), cmap='RdBu', center=0, add_colorbar=False)
            ax.coastlines()
            ax.set_title(title)
            fig.colorbar(im, ax=ax, orientation='horizontal', pad=0.05)
            idx += 1

    # Remove empty subplots
    for j in range(idx, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, "spatial_mean_differences.png"), dpi=300)
    print(f"Saved spatial differences map to {OUT_DIR}/spatial_mean_differences.png")

def plot_timeseries_basin_average(results):
    """
    Plots the spatial average time series for key variables.
    """
    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

    if 'SM_OPL' in results and 'SM_DA' in results:
        # Spatial mean (ignoring NaNs)
        ts_sm_opl = results['SM_OPL'].mean(dim=['lat', 'lon'])
        ts_sm_da = results['SM_DA'].mean(dim=['lat', 'lon'])
        
        axes[0].plot(ts_sm_opl.time, ts_sm_opl, label='OPL', color='blue', linestyle='--')
        axes[0].plot(ts_sm_da.time, ts_sm_da, label='DA', color='red')
        axes[0].set_ylabel('Total Soil Moisture [kg/m2]')
        axes[0].set_title('Basin-Averaged Total Soil Moisture')
        axes[0].legend()

    if 'Qs_Diff' in results and 'Qsb_Diff' in results:
        ts_qs_diff = results['Qs_Diff'].mean(dim=['lat', 'lon'])
        ts_qsb_diff = results['Qsb_Diff'].mean(dim=['lat', 'lon'])
        
        axes[1].plot(ts_qs_diff.time, ts_qs_diff, label='Surface Runoff (\u0394Qs)', color='orange')
        axes[1].plot(ts_qsb_diff.time, ts_qsb_diff, label='Baseflow (\u0394Qsb)', color='purple')
        axes[1].set_ylabel('Runoff Difference [kg/m2/s]')
        axes[1].set_title('Runoff Increments (DA - OPL)')
        axes[1].legend()

    if 'ET_Diff' in results:
        ts_et_diff = results['ET_Diff'].mean(dim=['lat', 'lon'])
        axes[2].plot(ts_et_diff.time, ts_et_diff, label='Evapotranspiration (\u0394ET)', color='green')
        axes[2].set_ylabel('ET Difference [kg/m2/s]')
        axes[2].set_title('Evapotranspiration Increments (DA - OPL)')
        axes[2].legend()

    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, "basin_timeseries.png"), dpi=300)
    print(f"Saved basin timeseries to {OUT_DIR}/basin_timeseries.png")

if __name__ == "__main__":
    print("Loading datasets...")
    ds_opl = load_lis_outputs(DIR_OPL)
    ds_da = load_lis_outputs(DIR_DA)
    
    if ds_opl is not None and ds_da is not None:
        print("Computing differences and budget closure metrics...")
        results = compute_budget_and_differences(ds_opl, ds_da)
        
        print("Generating diagnostic plots...")
        plot_spatial_differences(results)
        plot_timeseries_basin_average(results)
        print("Post-processing diagnostic run complete.")
    else:
        print("Required netCDF data not found. Please adjust paths.")
